name: Your Prompt
description: This is a test file to take prompts as an input
body:
- type: markdown
  attributes:
    value: "## Welcome!"
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to add Prompts
- type: input
      id: Prompt_Title
      attributes:
        label: Prompt Title
       placeholder: Prompt Title
      validations:
       required: true
- type: textarea
    id: new_prompt
    attributes:
      label: 
      description: A clear and concise description of what the bug is, and any additional context.
      placeholder: Tell us what you see!
    validations:
      required: true
- type: input
    id: gihub_user_name
    attributes:
      label: Github User Name
      placeholder: Github User Name
    validations:
      required: true
- type: input
    id: github_profile
    attributes:
      label: Github profile Url
      placeholder: https://github.com/github_profile
    validations:
      required: true
- type: checkboxes
    id: isbychatgpt
    attributes:
      label: Code of Conduct
      description: If your prompt was generated by ChatGPT, please check the checkbox
      options:
        - label: This Prompt is generated by ChatGPT
      required: false
