name: Your Prompt
description: This is a test file to take prompts as an input
body:
- type: markdown
  attributes:
    value: "## Welcome!"
- type: markdown
  attributes:
    value: "Thanks for taking the time to add Prompts"
- type: input
  id: pr_title
  attributes:
    label: Prompt Title
    placeholder: "Prompt Title"
  validations:
    required: true
- type: textarea
  id: new_prompt
  attributes:
    label: ChatGPT Prompt
    description: "A clear and concise prompt"
    placeholder: "Write your Awesome ChatGPT Prompt"
  validations:
    required: true
- type: input
  id: gihub_user_name
  attributes:
    label: Github User Name
    placeholder: "Github User Name"
  validations:
    required: true
- type: input
  id: github_profile
  attributes:
    label: Github profile Url
    placeholder: "https://github.com/github_profile"
  validations:
    required: true
- type: checkboxes
  id: isbychatgpt
  attributes:
    label: IsByChatGPT
    description: "If your prompt was generated by ChatGPT, please check the checkbox"
    options:
      - label: This Prompt is generated by ChatGPT
        required: false
